[project]
protostar-version = "0.9.2"
cairo-path = ["lib", "./lib/cairo_contracts/src"]
lib-path = "lib"

[contracts]
cairo0resolver = ["src/cairo0resolver.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
